image: drupalpod/drupalpod-gitpod-base:20220322
# ddev and composer are running as part of the prebuild
# when starting a workspace all docker images are ready
tasks:
  - init: |
      .gitpod/utils/send-a-message-gcs.sh > /tmp/output1.txt
      ddev debug download-images
      .gitpod/utils/ddev-in-gitpod-setup.sh
      .gitpod/drupal/envs-prep/prepare-environments-gcs.sh > /tmp/output2.txt
      .gitpod/drupal/envs-prep/set-default-environment.sh
    command: |
      .gitpod/utils/ddev-in-gitpod-setup.sh
      .gitpod/utils/env-setup.sh
      .gitpod/drupal/ssh/01-check-private-ssh.sh
      .gitpod/drupal/drupalpod-setup.sh

# VScode xdebug extension
vscode:
  extensions:
    # PHP extensions.
    - felixfbecker.php-debug
    - wongjn.php-sniffer
    - neilbrayfield.php-docblocker
    - bmewburn.vscode-intelephense-client

    # Twig extensions.
    - mblode.twig-language-2

    # Help extensions.
    - drupal-mentoring.drupalpod-ext

    # Bash extensions.
    - timonwong.shellcheck
    - rogalmic.bash-debug

ports:
  # Used by ddev - local db clients
  - port: 3306
    onOpen: ignore
  # Used by MailHog
  - port: 8027
    onOpen: ignore
  # Used by phpMyAdmin
  - port: 8036
    onOpen: ignore
  # Direct-connect ddev-webserver port that is the main port
  - port: 8080
    onOpen: ignore
  # Ignore host https port
  - port: 8443
    onOpen: ignore
  # xdebug port
  - port: 9003
    onOpen: ignore

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: true
