image:
  file: .gitpod/.gitpod.Dockerfile

# ddev and composer are running as part of the prebuild
# when starting a workspace all docker images are ready
tasks:
  - init: |
      .gitpod/download-ddev-images.sh
      .gitpod/setup-ddev.sh
      ddev composer run-script post-root-package-install
    command: |
      .gitpod/setup-ddev.sh
      .gitpod/drupal/setup-private-ssh.sh
      .gitpod/drupal/pull-issue-fork.sh

# VScode xdebug extension
vscode:
  extensions:
    - felixfbecker.php-debug@1.13.0:WX8Y3EpQk3zgahy41yJtNQ==

ports:
  # Used by projector
  - port: 6942
    onOpen: ignore
    visibility: private
  # Direct-connect ddev-webserver port that is the main port
  - port: 8080
    visibility: private
  # Currently un-notified and unsupported mailhog http port
  - port: 8025
    onOpen: ignore
    visibility: private
  # Currently un-notified and unsupported mailhog https port
  - port: 8026
    onOpen: ignore
    visibility: private
  # Currently un-notified and unsupported phpmyadmin http port
  - port: 8036
    onOpen: ignore
    visibility: private
  # Currently un-notified and unsupported phpmyadmin https port
  - port: 8037
    onOpen: ignore
    visibility: private
  # router http port that we're ignoring.
  - port: 8888
    onOpen: ignore
    visibility: private
  # router https port that we're ignoring.
  - port: 8889
    onOpen: ignore
    visibility: private
  # xdebug port
  - port: 9000
    onOpen: ignore
    visibility: private
  # projector port
  - port: 9999
    visibility: private

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: true
