image: drupalpod/drupalpod-gitpod-base:20240419

# DDEV and composer are running as part of the prebuild
# when starting a workspace all docker images are ready
tasks:
  - init: |
      .gitpod/utils/send-a-message-gcs.sh > /tmp/output1.txt
      .gitpod/utils/ddev-in-gitpod-setup.sh
      .gitpod/utils/set-base-environment.sh
    command: |
      # Temporary fix for wrong value of GITPOD_REPO_ROOT when opening a Gitpod snapshot
      # Todo: remove this when this issue is resolved - https://github.com/gitpod-io/gitpod/issues/9804
      if [ "$GITPOD_REPO_ROOT" == '/workspace' ]; then
        export GITPOD_REPO_ROOT="$THEIA_WORKSPACE_ROOT"
      fi
      .gitpod/utils/ddev-in-gitpod-setup.sh
      .gitpod/utils/env-setup.sh
      .gitpod/drupal/ssh/01-check-private-ssh.sh
      .gitpod/drupal/drupalpod-setup/drupalpod-setup.sh

# VScode xdebug extension
vscode:
  extensions:
    # PHP extensions.
    - felixfbecker.php-debug
    - wongjn.php-sniffer
    - neilbrayfield.php-docblocker
    - bmewburn.vscode-intelephense-client
    - andrewdavidblum.drupal-smart-snippets

    # Twig extensions.
    - mblode.twig-language-2

    # Help extensions.
    - drupal-mentoring.drupalpod-ext

    # Bash extensions.
    - timonwong.shellcheck
    - rogalmic.bash-debug

ports:
  # Used by JS projects
  - port: 3000
    onOpen: ignore
  # Used by DDEV - local db clients
  - port: 3306
    name: Database
    description: Access for local database clients
    onOpen: ignore
  # Used by JS projects
  - port: 5000
    onOpen: ignore
  # Used by MailHog
  - port: 8027
    name: MailHog
    description: MailHog
    onOpen: ignore
  # Used by phpMyAdmin
  - port: 8036
    name: phpMyAdmin
    description: phpMyAdmin
    onOpen: ignore
  # Direct-connect DDEV-webserver port that is the main port
  - port: 8080
    name: website
    description: website
    onOpen: ignore
  # Ignore host https port
  - port: 8443
    name: (not used)
    description: host https port
    onOpen: ignore
  # xdebug port
  - port: 9003
    name: xdebug
    description: xdebug
    onOpen: ignore
