#!/bin/bash

## Description: Run programs in container, based on current host directory
## Usage: exec_d [args]
## Example: "ddev exec_d yarn"

if [ -z "$1" ]; then
  echo "No argument supplied"
  exit 1
fi

if [ "${GITPOD_NORMALIZE_EXEC_ARGUMENTS:-1}" = 1 ] && [ -n "${GITPOD_REPO_ROOT}" ]; then
  # Replace all references to the absolute path to the repo root.
  # This will ensure IDEs like PHPStorm can pass files into it without issue.
  arguments=()
  for arg in "$@"; do
    new_arg="${arg//${GITPOD_REPO_ROOT}//var/www/html}"
    arguments+=("$new_arg")
  done
else
  arguments=("$@")
fi

ddev exec -d /var/www/html/"$(echo "$PWD" | cut -d'/' -f4-)" "${arguments[@]}"
