#!/bin/bash

## Description: Run PHP_CodeSniffer's code beautifier
## Usage: phpcbf [flags] [args]
## Example: "ddev phpcbf --standard=core/phpcs.xml.dist index.php" or "ddev phpcbf index.php"
## HostWorkingDir: true
## ExecRaw: true

if ! command -v phpcbf >/dev/null; then
  echo "phpcbf is not available. You may need to 'ddev composer require squizlabs/php_codesniffer'"
  exit 1
fi
phpcbf "$@"
