#!/bin/bash

## Description: Run PHPUnit
## Usage: phpunit [flags] [args]
## Example: "ddev phpunit --group big_pipe" or "ddev phpunit core/modules/action"

mkdir -p /var/www/html/web/sites/simpletest/browser_output

cd web

BROWSERTEST_OUTPUT_DIRECTORY=/var/www/html/web/sites/simpletest/browser_output \
BROWSERTEST_OUTPUT_BASE_URL=http://localhost:8080 \
SIMPLETEST_DB="mysql://db:db@db/db" \
SIMPLETEST_BASE_URL="http://localhost" \
php ../vendor/bin/phpunit -c core/phpunit.xml.dist $@
