#!/bin/bash

#ddev-generated
## Command provided by https://github.com/ddev/ddev-drupal-contrib
## Description: Run stylelint inside the web container
## Usage: stylelint [flags] [args]
## Example: "ddev stylelint" or "ddev stylelint --fix"
## ProjectTypes: drupal8,drupal9,drupal10
## ExecRaw: true

if yarn --cwd "$DDEV_DOCROOT/core" stylelint --version >/dev/null ; then
  yarn --color --cwd "$DDEV_DOCROOT/core" --config ./.stylelintrc.json stylelint /var/www/html/repos/project_browser/**/*.css "$@"
else
  echo "stylelint is not available. You may need to 'ddev yarn --cwd $DDEV_DOCROOT/core install'"
  exit 1
fi
